# Generated by Django 3.1.3 on 2020-11-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='TAG')),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('Planta', 'Planta'), ('Sistema', 'Sistema'), ('Equipamento', 'Equipamento'), ('Peça', 'Peça')], default='Planta', max_length=50)),
                ('criticidade', models.TextField()),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descriçao')),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='TAG do elemento pai')),
                ('localizacao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Localização')),
                ('link_historico', models.CharField(blank=True, max_length=255, null=True)),
                ('link_pm', models.CharField(blank=True, max_length=255, null=True)),
                ('link_foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Árvore de Equipamento',
                'verbose_name_plural': 'Árvore de Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tag', models.CharField(max_length=20)),
                ('data_incial', models.DateField(default=datetime.date.today, verbose_name='Data de Iníco')),
                ('data_final', models.DateField(default=datetime.date.today, verbose_name='Data Final')),
                ('descricao', models.TextField(help_text='Descreva o serviço à ser realizado', verbose_name='Descrição do Serviço')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de Serviços',
            },
        ),
    ]
