# Generated by Django 3.1.3 on 2020-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvore',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
